- .appveyor.yml
- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_python3.7.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/win_python3.7.yaml
- README.md
- recipe/meta.yaml
> Enable py37 builds

- recipe/meta.yaml
> Add missed entry point

- recipe/meta.yaml
> Add all dvc deps

- recipe/meta.yaml
> dvc v0.57.0

- .gitignore
- recipe/build.patch
- recipe/meta.yaml
Checklist
This is required for further work regarding https://github.com/iterative/dvc/pull/2679/files
> create build patch for conda detection

- recipe/meta.yaml
> recipe: add simple tests

- recipe/meta.yaml
https://github.com/conda-forge/dvc-feedstock/pull/63#discussion_r357984049
Checklist
> limit tqdm version to <5

- recipe/meta.yaml
Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>
Checklist
> meta: match requirements with the core project

- recipe/meta.yaml
> recipe: update deps

- recipe/meta.yaml
> meta: update pydrive2 version

- recipe/meta.yaml
> meta: don't forget pygtrie

- recipe/meta.yaml
Accidental leftover from debug :(
Checklist
> recipe: uncomment remotes

- recipe/meta.yaml
Fixes https://github.com/iterative/dvc/issues/4318
Checklist
> don't forget to include toml

- recipe/meta.yaml
Checklist
Where are these packages documented in the dvc documentation?
> Fix "power user path" instructions

- recipe/meta.yaml
Checklist
Once both #208 and conda-forge/gcsfs-feedstock/pull/33 are merged, do the following:
- Wait 90 minutes for the conda-forge CDN to update. (Run `conda search gcsfs` to check the status.)
- Once the new build appears on conda-forge, write the following in a comment in this PR, adding a @ at the front of conda-forge-admin in order to ping the bot:
> conda-forge-admin, please restart ci
- Fix any additional problems.
- Bump the build number!!!!! (I can't do it beforehand since I don't know the order in which the upstream issues will resolve.)
- Merge this.
> Remove upstream ujson dep

- recipe/meta.yaml
Checklist
Once both #208 is merged and the issue described in conda-forge/filesystem-spec-feedstock/issues/42 and conda-forge/filesystem-spec-feedstock#43 is resolved, then do the following:
- Write the following in a comment in this PR, adding a @ at the front of conda-forge-admin in order to ping the bot:
> conda-forge-admin, please restart ci
- Fix any additional problems.
- Bump the build number!!!!! (I can't do it beforehand since I don't know the order in which the upstream issues will resolve.)
- Merge this.
> Remove temporary upstream importlib-meta dependency

- .github/CODEOWNERS
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
It should be in agreement with https://github.com/iterative/dvc/blob/2.0.18/setup.py
Checklist
> Fix incorrect fsspec version

- recipe/meta.yaml
> add dvc-webdav

- recipe/meta.yaml
> meta: update rich

- README.md
- recipe/meta.yaml
Closes https://github.com/conda-forge/dvc-feedstock/issues/253. The issue is fixed on ftfy-feedstock.
Checklist
> Unpin python-benedict

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
Hey all, I'm looking to reduce my notifications. I haven't been doing much around here lately, and the rest of you are doing an excellent job.
It's been nice to meet some of you, and feel free to ping me if you'd like my help. :smile:
Checklist
> [ci-skip] Remove @maresb as maintainer

- recipe/meta.yaml
Fixes https://github.com/iterative/dvc/issues/9199
Checklist
> meta: fix platformdirs lower limit

- recipe/meta.yaml
> meta: don't forget setuptools-scm

- recipe/meta.yaml
> Update scmrepo requirement

- .azure-pipelines/azure-pipelines-linux.yml
- .scripts/build_steps.sh
- recipe/meta.yaml
Python 3.8 is not supported by DVC anymore.
> bump python version, 3.8 is not supported anymore

- recipe/meta.yaml
Related to https://github.com/iterative/dvc/pull/10354
Checklist
> add attrs as an explicit dependency

- recipe/meta.yaml
But keep python at the top.
Checklist
> sort dependencies
